# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import unittest
from tests.http_response_catcher import HttpResponseCatcher
from shellev.configuration import Configuration
from shellev.shellev_client import ShellevClient


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = ShellevClient(config=cls.config)

        bearer_auth_token = cls.client.bearer_auth.fetch_token()
        client_credentials_auth_credentials = cls.config.client_credentials_auth_credentials\
            .clone_with(o_auth_token=bearer_auth_token)
        cls.config = cls.config.clone_with(client_credentials_auth_credentials=client_credentials_auth_credentials)

        cls.client = ShellevClient(config=cls.config)

    @staticmethod
    def create_configuration():
        return Configuration(http_call_back=HttpResponseCatcher())
