# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from shellev.api_helper import APIHelper
from shellev.models.chargesession_start_body import ChargesessionStartBody


class ChargingControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(ChargingControllerTests, cls).setUpClass()
        cls.controller = cls.client.charging
        cls.response_catcher = cls.controller.http_call_back

    # This API initiates to start a session on a EVSE (Electric Vehicle Supply Equipement). When the EV Charge Card number and the unique EVSE ID on the location is provided, the session is initiated. 
    #
    #Please note that this is an asynchronous request, the request will be passed on to the operator/platform to be processed further. 
    #
    def test_start_charge_session(self):
        # Parameters for the API call
        request_id = 'eb621f45-a543-4d9a-a934-2f223b263c42'
        body = None

        # Perform the API call through the SDK function
        result = self.controller.start_charge_session(request_id, body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"RequestId":"9d2dee33-7803-485a-a2b1-2c7538e597ee","Status":"SUCC'
            'ESS","Data":[{"SessionId":"c3e332f0-1bb2-4f50-a96b-e075bbb71e68"}]'
            '}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # This API retrieves the list of active sessions for a given set of EMAIds
    def test_active(self):
        # Parameters for the API call
        ema_id = 'NL-TNM-C0216599X-A'
        request_id = 'eb621f45-a543-4d9a-a934-2f223b263c42'

        # Perform the API call through the SDK function
        result = self.controller.active(ema_id, request_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"RequestId":"9d2dee33-7803-485a-a2b1-2c7538e597ee","Status":"SUCC'
            'ESS","Data":[{"EmaId":"NL-TNM-C0216599X-A","EvseId":"NL*TNM*EVIRTU'
            'ALCP0002*0","Id":"260f17a9-52d4-4b40-ae74-83832b538975","StartedAt'
            '":"2022-10-21T09:11:23.455Z","SessionState":"started","SessionCode'
            '":null,"SessionMessage":null,"UserId":"96f69b3b-8ad4-487a-baaa-f1d'
            '3db741e88"}]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

