# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AccessibilityStatusEnum(object):

    """Implementation of the 'accessibilityStatus' enum.

    Accessibility Status

    Attributes:
        FREEPUBLIC: The enum member of type str.
        PAYINGPUBLIC: The enum member of type str.
        RESTRICTED: The enum member of type str.
        UNSPECIFIED: The enum member of type str.

    """
    FREEPUBLIC = 'FreePublic'

    PAYINGPUBLIC = 'PayingPublic'

    RESTRICTED = 'Restricted'

    UNSPECIFIED = 'Unspecified'

