# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AccessibilityStatusEnum(object):

    """Implementation of the 'AccessibilityStatus' enum.

    Accessibility Status

    Attributes:
        FREEPUBLIC: TODO: type description here.
        PAYINGPUBLIC: TODO: type description here.
        RESTRICTED: TODO: type description here.
        UNSPECIFIED: TODO: type description here.

    """
    FREEPUBLIC = 'FreePublic'

    PAYINGPUBLIC = 'PayingPublic'

    RESTRICTED = 'Restricted'

    UNSPECIFIED = 'Unspecified'

