# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellev.api_helper import APIHelper
from shellev.models.data_active import DataActive


class ActiveResponse200Json(object):

    """Implementation of the 'activeResponse200Json' model.

    TODO: type model description here.

    Attributes:
        request_id (uuid|str): A unique request id in GUID format. The value
            is written to the Shell API Platform audit log for end to end
            traceability of a request.
        status (ActiveResponse200JsonStatusEnum): Indicates overall status of
            the request
        data (List[DataActive]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_id": 'RequestId',
        "status": 'Status',
        "data": 'Data'
    }

    _optionals = [
        'data',
    ]

    def __init__(self,
                 request_id=None,
                 status=None,
                 data=APIHelper.SKIP):
        """Constructor for the ActiveResponse200Json class"""

        # Initialize members of the class
        self.request_id = request_id 
        self.status = status 
        if data is not APIHelper.SKIP:
            self.data = data 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        request_id = dictionary.get("RequestId") if dictionary.get("RequestId") else None
        status = dictionary.get("Status") if dictionary.get("Status") else None
        data = None
        if dictionary.get('Data') is not None:
            data = [DataActive.from_dictionary(x) for x in dictionary.get('Data')]
        else:
            data = APIHelper.SKIP
        # Return an object of this model
        return cls(request_id,
                   status,
                   data)
