# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ActiveResponse200JsonStatusEnum(object):

    """Implementation of the 'activeResponse200JsonStatus' enum.

    Indicates overall status of the request

    Attributes:
        SUCCESS: The enum member of type str.
        FAILED: The enum member of type str.

    """
    SUCCESS = 'SUCCESS'

    FAILED = 'FAILED'

