# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ConnectorVOUpdatedByEnum(object):

    """Implementation of the 'ConnectorVOUpdatedBy' enum.

    Source of the last update

    Attributes:
        FEED: TODO: type description here.
        ADMIN: TODO: type description here.
        TARIFFSERVICE: TODO: type description here.
        DEFAULTS: TODO: type description here.

    """
    FEED = 'Feed'

    ADMIN = 'Admin'

    TARIFFSERVICE = 'TariffService'

    DEFAULTS = 'Defaults'

