"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.electrical_properties_v_2 import (
    ElectricalPropertiesV2,
)


class ConnectorV2(object):
    """Implementation of the 'ConnectorV2' model.

    An EVSE can have one or many Connectors. Each Connector will normally have a
    different socket / cable and only one can be used to charge at a time.

    Attributes:
        uid (str): Internal identifier used to refer to this Connector
        external_id (str): Identifier of the Evse as given by the Operator, unique
            for the containing EVSE'
        connector_type (ConnectorVOConnectorTypeEnum): Type of the connector in the
            EVSE unit.
        electrical_properties (ElectricalPropertiesV2): Electrical Properties of the
            Connector

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uid": "uid",
        "external_id": "externalId",
        "connector_type": "connectorType",
        "electrical_properties": "electricalProperties",
    }

    _optionals = [
        "uid",
        "external_id",
        "connector_type",
        "electrical_properties",
    ]

    def __init__(
        self,
        uid=APIHelper.SKIP,
        external_id=APIHelper.SKIP,
        connector_type=APIHelper.SKIP,
        electrical_properties=APIHelper.SKIP):
        """Initialize a ConnectorV2 instance."""
        # Initialize members of the class
        if uid is not APIHelper.SKIP:
            self.uid = uid
        if external_id is not APIHelper.SKIP:
            self.external_id = external_id
        if connector_type is not APIHelper.SKIP:
            self.connector_type = connector_type
        if electrical_properties is not APIHelper.SKIP:
            self.electrical_properties = electrical_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        uid =\
            dictionary.get("uid")\
            if dictionary.get("uid")\
                else APIHelper.SKIP
        external_id =\
            dictionary.get("externalId")\
            if dictionary.get("externalId")\
                else APIHelper.SKIP
        connector_type =\
            dictionary.get("connectorType")\
            if dictionary.get("connectorType")\
                else APIHelper.SKIP
        electrical_properties =\
            ElectricalPropertiesV2.from_dictionary(
                dictionary.get("electricalProperties"))\
                if "electricalProperties" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(uid,
                   external_id,
                   connector_type,
                   electrical_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _uid=(
            self.uid
            if hasattr(self, "uid")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _connector_type=(
            self.connector_type
            if hasattr(self, "connector_type")
            else None
        )
        _electrical_properties=(
            self.electrical_properties
            if hasattr(self, "electrical_properties")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"uid={_uid!r}, "
            f"external_id={_external_id!r}, "
            f"connector_type={_connector_type!r}, "
            f"electrical_properties={_electrical_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _uid=(
            self.uid
            if hasattr(self, "uid")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _connector_type=(
            self.connector_type
            if hasattr(self, "connector_type")
            else None
        )
        _electrical_properties=(
            self.electrical_properties
            if hasattr(self, "electrical_properties")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"uid={_uid!s}, "
            f"external_id={_external_id!s}, "
            f"connector_type={_connector_type!s}, "
            f"electrical_properties={_electrical_properties!s}, "
            f")"
        )
