# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ConnectorVOConnectorTypeEnum(object):

    """Implementation of the 'connectorVOConnectorType' enum.

    Type of the connector in the EVSE unit.

    Attributes:
        AVCON: TODO: type description here.
        DOMESTIC: TODO: type description here.
        INDUSTRIAL2PDC: TODO: type description here.
        INDUSTRIALPNEAC: TODO: type description here.
        INDUSTRIAL3PEAC: TODO: type description here.
        INDUSTRIAL3PENAC: TODO: type description here.
        TYPE1: TODO: type description here.
        TYPE1COMBO: TODO: type description here.
        TYPE2: TODO: type description here.
        TYPE2COMBO: TODO: type description here.
        TYPE3: TODO: type description here.
        LPI: TODO: type description here.
        NEMA520: TODO: type description here.
        SAEJ1772: TODO: type description here.
        SPI: TODO: type description here.
        TEPCOCHADEMO: TODO: type description here.
        TESLA: TODO: type description here.
        UNSPECIFIED: TODO: type description here.

    """
    AVCON = 'Avcon'

    DOMESTIC = 'Domestic'

    INDUSTRIAL2PDC = 'Industrial2PDc'

    INDUSTRIALPNEAC = 'IndustrialPneAc'

    INDUSTRIAL3PEAC = 'Industrial3PEAc'

    INDUSTRIAL3PENAC = 'Industrial3PENAc'

    TYPE1 = 'Type1'

    TYPE1COMBO = 'Type1Combo'

    TYPE2 = 'Type2'

    TYPE2COMBO = 'Type2Combo'

    TYPE3 = 'Type3'

    LPI = 'LPI'

    NEMA520 = 'Nema520'

    SAEJ1772 = 'SAEJ1772'

    SPI = 'SPI'

    TEPCOCHADEMO = 'TepcoCHAdeMO'

    TESLA = 'Tesla'

    UNSPECIFIED = 'Unspecified'

