# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DataRetrieveSessionStateEnum(object):

    """Implementation of the 'dataRetrieveSessionState' enum.

    Describes the session state

    Attributes:
        STARTED: TODO: type description here.
        STOPPED: TODO: type description here.
        STARTREQUESTED: TODO: type description here.
        STOPREQUESTED: TODO: type description here.
        FAILEDTOSTART: TODO: type description here.
        FAILEDTOSTOP: TODO: type description here.

    """
    STARTED = 'started'

    STOPPED = 'stopped'

    STARTREQUESTED = 'start-requested'

    STOPREQUESTED = 'stop-requested'

    FAILEDTOSTART = 'failed-to-start'

    FAILEDTOSTOP = 'failed-to-stop'

