# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DataRetrieveSessionCodeEnum(object):

    """Implementation of the 'dataRetrieveSessionCode' enum.

    Session code e.g InternalError

    Attributes:
        INTERNALERROR: TODO: type description here.
        SERVICEUNAVAILABLE: TODO: type description here.
        CHARGETOKENNOTSUPPORTED: TODO: type description here.
        SESSIONINVALID: TODO: type description here.
        EVNOTCONNECTEDTOEVSE: TODO: type description here.
        EVSEINUSE: TODO: type description here.
        EVSEOUTOFSERVICE: TODO: type description here.
        EVSENOTFOUND: TODO: type description here.
        EVSENOTSUPPORTED: TODO: type description here.

    """
    INTERNALERROR = 'InternalError'

    SERVICEUNAVAILABLE = 'ServiceUnavailable'

    CHARGETOKENNOTSUPPORTED = 'ChargeTokenNotSupported'

    SESSIONINVALID = 'SessionInvalid'

    EVNOTCONNECTEDTOEVSE = 'EvNotConnectedToEvse'

    EVSEINUSE = 'EvseInUse'

    EVSEOUTOFSERVICE = 'EvseOutOfService'

    EVSENOTFOUND = 'EvseNotFound'

    EVSENOTSUPPORTED = 'EvseNotSupported'

