# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ElectricalPropertiesPowerTypeEnum(object):

    """Implementation of the 'ElectricalPropertiesPowerType' enum.

    Power Type used in this connector.

    Attributes:
        AC1PHASE: TODO: type description here.
        AC3PHASE: TODO: type description here.
        DC: TODO: type description here.

    """
    AC1PHASE = 'AC1Phase'

    AC3PHASE = 'AC3Phase'

    DC = 'DC'

