# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EnvEnum(object):

    """Implementation of the 'env' enum.

    TODO: type enum description here.

    Attributes:
        ENUM_APITESTSHELLCOM: TODO: type description here.
        ENUM_APISHELLCOM: TODO: type description here.

    """
    ENUM_APITESTSHELLCOM = 'api-test.shell.com'

    ENUM_APISHELLCOM = 'api.shell.com'

