# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InlineResponse202Data(object):

    """Implementation of the 'inline_response_202_Data' model.

    TODO: type model description here.

    Attributes:
        session_id (str): Session Id for tracking.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "session_id": 'SessionId'
    }

    def __init__(self,
                 session_id=None):
        """Constructor for the InlineResponse202Data class"""

        # Initialize members of the class
        self.session_id = session_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        session_id = dictionary.get("SessionId") if dictionary.get("SessionId") else None
        # Return an object of this model
        return cls(session_id)
