# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellev.models.inline_response_202_data import InlineResponse202Data


class InlineResponse202(object):

    """Implementation of the 'inline_response_202' model.

    TODO: type model description here.

    Attributes:
        request_id (uuid|str): Mandatory UUID (according to RFC 4122
            standards) for requests and responses. This will be played back in
            the response from the request.
        status (InlineResponse202StatusEnum): Indicates overall status of the
            request
        data (List[InlineResponse202Data]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_id": 'requestId',
        "status": 'status',
        "data": 'data'
    }

    def __init__(self,
                 request_id=None,
                 status=None,
                 data=None):
        """Constructor for the InlineResponse202 class"""

        # Initialize members of the class
        self.request_id = request_id 
        self.status = status 
        self.data = data 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        request_id = dictionary.get("requestId") if dictionary.get("requestId") else None
        status = dictionary.get("status") if dictionary.get("status") else None
        data = None
        if dictionary.get('data') is not None:
            data = [InlineResponse202Data.from_dictionary(x) for x in dictionary.get('data')]
        # Return an object of this model
        return cls(request_id,
                   status,
                   data)
