# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LocationsMarkersEvseStatusEnum(object):

    """Implementation of the 'locationsMarkersEvseStatus' enum.

    TODO: type enum description here.

    Attributes:
        AVAILABLE: TODO: type description here.
        OCCUPIED: TODO: type description here.
        UNAVAILABLE: TODO: type description here.
        UNKNOWN: TODO: type description here.

    """
    _all_values = ['Available', 'Occupied', 'Unavailable', 'Unknown']
    AVAILABLE = 'Available'

    OCCUPIED = 'Occupied'

    UNAVAILABLE = 'Unavailable'

    UNKNOWN = 'Unknown'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   