"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.coordinates import Coordinates


class MultiLocationMarkerV2(object):
    """Implementation of the 'MultiLocationMarkerV2' model.

    A Marker is a place on the map that represent multiple Locations at the same spot

    Attributes:
        coordinates (Coordinates): Coordinates of the Shell Recharge Site Location
        location_count (float): Number of Locations that this Marker represents in
            the given set of bounds
        evse_count (float): Total number of Evses in Locations that this Marker
            represents
        max_power (float): Maximum power in kW across all locations grouped in this
            marker (disregarding availability)
        operator_name (str): Operator of this Shell Recharge Location
        marker_type (str): Type of the Marker, in this case it will always be
            MultiLocation

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "marker_type": "markerType",
        "coordinates": "coordinates",
        "location_count": "locationCount",
        "evse_count": "evseCount",
        "max_power": "maxPower",
        "operator_name": "operatorName",
    }

    _optionals = [
        "coordinates",
        "location_count",
        "evse_count",
        "max_power",
        "operator_name",
    ]

    def __init__(
        self,
        coordinates=APIHelper.SKIP,
        location_count=APIHelper.SKIP,
        evse_count=APIHelper.SKIP,
        max_power=APIHelper.SKIP,
        operator_name=APIHelper.SKIP):
        """Initialize a MultiLocationMarkerV2 instance."""
        # Initialize members of the class
        if coordinates is not APIHelper.SKIP:
            self.coordinates = coordinates
        if location_count is not APIHelper.SKIP:
            self.location_count = location_count
        if evse_count is not APIHelper.SKIP:
            self.evse_count = evse_count
        if max_power is not APIHelper.SKIP:
            self.max_power = max_power
        if operator_name is not APIHelper.SKIP:
            self.operator_name = operator_name
        self.marker_type = "MultiLocation"

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        coordinates =\
            Coordinates.from_dictionary(
                dictionary.get("coordinates"))\
                if "coordinates" in dictionary.keys()\
                else APIHelper.SKIP
        location_count =\
            dictionary.get("locationCount")\
            if dictionary.get("locationCount")\
                else APIHelper.SKIP
        evse_count =\
            dictionary.get("evseCount")\
            if dictionary.get("evseCount")\
                else APIHelper.SKIP
        max_power =\
            dictionary.get("maxPower")\
            if dictionary.get("maxPower")\
                else APIHelper.SKIP
        operator_name =\
            dictionary.get("operatorName")\
            if dictionary.get("operatorName")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(coordinates,
                   location_count,
                   evse_count,
                   max_power,
                   operator_name)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.marker_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("markerType"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _coordinates=(
            self.coordinates
            if hasattr(self, "coordinates")
            else None
        )
        _location_count=(
            self.location_count
            if hasattr(self, "location_count")
            else None
        )
        _evse_count=(
            self.evse_count
            if hasattr(self, "evse_count")
            else None
        )
        _max_power=(
            self.max_power
            if hasattr(self, "max_power")
            else None
        )
        _operator_name=(
            self.operator_name
            if hasattr(self, "operator_name")
            else None
        )
        _marker_type=self.marker_type
        return (
            f"{self.__class__.__name__}("
            f"coordinates={_coordinates!r}, "
            f"location_count={_location_count!r}, "
            f"evse_count={_evse_count!r}, "
            f"max_power={_max_power!r}, "
            f"operator_name={_operator_name!r}, "
            f"marker_type={_marker_type!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _coordinates=(
            self.coordinates
            if hasattr(self, "coordinates")
            else None
        )
        _location_count=(
            self.location_count
            if hasattr(self, "location_count")
            else None
        )
        _evse_count=(
            self.evse_count
            if hasattr(self, "evse_count")
            else None
        )
        _max_power=(
            self.max_power
            if hasattr(self, "max_power")
            else None
        )
        _operator_name=(
            self.operator_name
            if hasattr(self, "operator_name")
            else None
        )
        _marker_type=self.marker_type
        return (
            f"{self.__class__.__name__}("
            f"coordinates={_coordinates!s}, "
            f"location_count={_location_count!s}, "
            f"evse_count={_evse_count!s}, "
            f"max_power={_max_power!s}, "
            f"operator_name={_operator_name!s}, "
            f"marker_type={_marker_type!s}, "
            f")"
        )
