# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OpeningHoursObjectWeekDayEnum(object):

    """Implementation of the 'openingHoursObjectWeekDay' enum.

    3 letter day of the week

    Attributes:
        SUN: TODO: type description here.
        MON: TODO: type description here.
        TUE: TODO: type description here.
        WED: TODO: type description here.
        THU: TODO: type description here.
        FRI: TODO: type description here.
        SAT: TODO: type description here.

    """
    SUN = 'Sun'

    MON = 'Mon'

    TUE = 'Tue'

    WED = 'Wed'

    THU = 'Thu'

    FRI = 'Fri'

    SAT = 'Sat'

