# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OpeningHoursObjectWeekDayEnum(object):

    """Implementation of the 'openingHoursObjectWeekDay' enum.

    3 letter day of the week

    Attributes:
        SUN: The enum member of type str.
        MON: The enum member of type str.
        TUE: The enum member of type str.
        WED: The enum member of type str.
        THU: The enum member of type str.
        FRI: The enum member of type str.
        SAT: The enum member of type str.

    """
    SUN = 'Sun'

    MON = 'Mon'

    TUE = 'Tue'

    WED = 'Wed'

    THU = 'Thu'

    FRI = 'Fri'

    SAT = 'Sat'

