"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class PowerRange(object):
    """Implementation of the 'PowerRange' model.

    Attributes:
        min (int): Minimum supported power in kW
        max (int): Maximum supported power in kW

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "min": "min",
        "max": "max",
    }

    def __init__(
        self,
        min=None,
        max=None):
        """Initialize a PowerRange instance."""
        # Initialize members of the class
        self.min = min
        self.max = max

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        min =\
            dictionary.get("min")\
            if dictionary.get("min")\
                else None
        max =\
            dictionary.get("max")\
            if dictionary.get("max")\
                else None

        # Return an object of this model
        return cls(min,
                   max)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _min=self.min
        _max=self.max
        return (
            f"{self.__class__.__name__}("
            f"min={_min!r}, "
            f"max={_max!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _min=self.min
        _max=self.max
        return (
            f"{self.__class__.__name__}("
            f"min={_min!s}, "
            f"max={_max!s}, "
            f")"
        )
