"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class PriceComponent(object):
    """Implementation of the 'PriceComponent' model.

    Attributes:
        mtype (TypeEnum): Type of the price component
        step_size (int): Step size in seconds for TIME-based components, in kWh for
            ENERGY-based components, or 1 for FLAT components
        price (float): Price per step in the specified currency for this price
            component
        vat (float): VAT percentage applicable to this price component

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "step_size": "stepSize",
        "price": "price",
        "vat": "vat",
    }

    def __init__(
        self,
        mtype=None,
        step_size=None,
        price=None,
        vat=None):
        """Initialize a PriceComponent instance."""
        # Initialize members of the class
        self.mtype = mtype
        self.step_size = step_size
        self.price = price
        self.vat = vat

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        step_size =\
            dictionary.get("stepSize")\
            if dictionary.get("stepSize")\
                else None
        price =\
            dictionary.get("price")\
            if dictionary.get("price")\
                else None
        vat =\
            dictionary.get("vat")\
            if dictionary.get("vat")\
                else None

        # Return an object of this model
        return cls(mtype,
                   step_size,
                   price,
                   vat)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _step_size=self.step_size
        _price=self.price
        _vat=self.vat
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"step_size={_step_size!r}, "
            f"price={_price!r}, "
            f"vat={_vat!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _step_size=self.step_size
        _price=self.price
        _vat=self.vat
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"step_size={_step_size!s}, "
            f"price={_price!s}, "
            f"vat={_vat!s}, "
            f")"
        )
