# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ResponseBaseStatusEnum(object):

    """Implementation of the 'responseBaseStatus' enum.

    Indicates overall status of the request

    Attributes:
        FAILED: TODO: type description here.
        PARTIAL_SUCCESS: TODO: type description here.
        SUCCESS: TODO: type description here.

    """
    FAILED = 'FAILED'

    PARTIAL_SUCCESS = 'PARTIAL_SUCCESS'

    SUCCESS = 'SUCCESS'

