"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from shellev.api_helper import APIHelper


class Restrictions(object):
    """Implementation of the 'Restrictions' model.

    Attributes:
        start_time (str): Valid from this time of the day (HH:mm)
        end_time (str): Valid until this time of the day (HH:mm)
        start_date (date): The model property of type date.
        end_date (date): The model property of type date.
        min_kwh (float): The model property of type float.
        max_kwh (float): The model property of type float.
        min_current (float): The model property of type float.
        max_current (float): The model property of type float.
        min_power (float): The model property of type float.
        max_power (float): The model property of type float.
        min_duration (int): Minimum session duration in seconds
        max_duration (int): Maximum session duration in seconds
        day_of_week (List[DayOfWeekEnum]): The model property of type
            List[DayOfWeekEnum].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "start_time": "startTime",
        "end_time": "endTime",
        "start_date": "startDate",
        "end_date": "endDate",
        "min_kwh": "minKwh",
        "max_kwh": "maxKwh",
        "min_current": "minCurrent",
        "max_current": "maxCurrent",
        "min_power": "minPower",
        "max_power": "maxPower",
        "min_duration": "minDuration",
        "max_duration": "maxDuration",
        "day_of_week": "dayOfWeek",
    }

    _optionals = [
        "start_time",
        "end_time",
        "start_date",
        "end_date",
        "min_kwh",
        "max_kwh",
        "min_current",
        "max_current",
        "min_power",
        "max_power",
        "min_duration",
        "max_duration",
        "day_of_week",
    ]

    def __init__(
        self,
        start_time=APIHelper.SKIP,
        end_time=APIHelper.SKIP,
        start_date=APIHelper.SKIP,
        end_date=APIHelper.SKIP,
        min_kwh=APIHelper.SKIP,
        max_kwh=APIHelper.SKIP,
        min_current=APIHelper.SKIP,
        max_current=APIHelper.SKIP,
        min_power=APIHelper.SKIP,
        max_power=APIHelper.SKIP,
        min_duration=APIHelper.SKIP,
        max_duration=APIHelper.SKIP,
        day_of_week=APIHelper.SKIP):
        """Initialize a Restrictions instance."""
        # Initialize members of the class
        if start_time is not APIHelper.SKIP:
            self.start_time = start_time
        if end_time is not APIHelper.SKIP:
            self.end_time = end_time
        if start_date is not APIHelper.SKIP:
            self.start_date = start_date
        if end_date is not APIHelper.SKIP:
            self.end_date = end_date
        if min_kwh is not APIHelper.SKIP:
            self.min_kwh = min_kwh
        if max_kwh is not APIHelper.SKIP:
            self.max_kwh = max_kwh
        if min_current is not APIHelper.SKIP:
            self.min_current = min_current
        if max_current is not APIHelper.SKIP:
            self.max_current = max_current
        if min_power is not APIHelper.SKIP:
            self.min_power = min_power
        if max_power is not APIHelper.SKIP:
            self.max_power = max_power
        if min_duration is not APIHelper.SKIP:
            self.min_duration = min_duration
        if max_duration is not APIHelper.SKIP:
            self.max_duration = max_duration
        if day_of_week is not APIHelper.SKIP:
            self.day_of_week = day_of_week

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        start_time =\
            dictionary.get("startTime")\
            if dictionary.get("startTime")\
                else APIHelper.SKIP
        end_time =\
            dictionary.get("endTime")\
            if dictionary.get("endTime")\
                else APIHelper.SKIP
        start_date = dateutil.parser.parse(
            dictionary.get("startDate")).date()\
            if dictionary.get("startDate") else APIHelper.SKIP
        end_date = dateutil.parser.parse(
            dictionary.get("endDate")).date()\
            if dictionary.get("endDate") else APIHelper.SKIP
        min_kwh =\
            dictionary.get("minKwh")\
            if dictionary.get("minKwh")\
                else APIHelper.SKIP
        max_kwh =\
            dictionary.get("maxKwh")\
            if dictionary.get("maxKwh")\
                else APIHelper.SKIP
        min_current =\
            dictionary.get("minCurrent")\
            if dictionary.get("minCurrent")\
                else APIHelper.SKIP
        max_current =\
            dictionary.get("maxCurrent")\
            if dictionary.get("maxCurrent")\
                else APIHelper.SKIP
        min_power =\
            dictionary.get("minPower")\
            if dictionary.get("minPower")\
                else APIHelper.SKIP
        max_power =\
            dictionary.get("maxPower")\
            if dictionary.get("maxPower")\
                else APIHelper.SKIP
        min_duration =\
            dictionary.get("minDuration")\
            if dictionary.get("minDuration")\
                else APIHelper.SKIP
        max_duration =\
            dictionary.get("maxDuration")\
            if dictionary.get("maxDuration")\
                else APIHelper.SKIP
        day_of_week =\
            dictionary.get("dayOfWeek")\
            if dictionary.get("dayOfWeek")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(start_time,
                   end_time,
                   start_date,
                   end_date,
                   min_kwh,
                   max_kwh,
                   min_current,
                   max_current,
                   min_power,
                   max_power,
                   min_duration,
                   max_duration,
                   day_of_week)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _start_time=(
            self.start_time
            if hasattr(self, "start_time")
            else None
        )
        _end_time=(
            self.end_time
            if hasattr(self, "end_time")
            else None
        )
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _min_kwh=(
            self.min_kwh
            if hasattr(self, "min_kwh")
            else None
        )
        _max_kwh=(
            self.max_kwh
            if hasattr(self, "max_kwh")
            else None
        )
        _min_current=(
            self.min_current
            if hasattr(self, "min_current")
            else None
        )
        _max_current=(
            self.max_current
            if hasattr(self, "max_current")
            else None
        )
        _min_power=(
            self.min_power
            if hasattr(self, "min_power")
            else None
        )
        _max_power=(
            self.max_power
            if hasattr(self, "max_power")
            else None
        )
        _min_duration=(
            self.min_duration
            if hasattr(self, "min_duration")
            else None
        )
        _max_duration=(
            self.max_duration
            if hasattr(self, "max_duration")
            else None
        )
        _day_of_week=(
            self.day_of_week
            if hasattr(self, "day_of_week")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"start_time={_start_time!r}, "
            f"end_time={_end_time!r}, "
            f"start_date={_start_date!r}, "
            f"end_date={_end_date!r}, "
            f"min_kwh={_min_kwh!r}, "
            f"max_kwh={_max_kwh!r}, "
            f"min_current={_min_current!r}, "
            f"max_current={_max_current!r}, "
            f"min_power={_min_power!r}, "
            f"max_power={_max_power!r}, "
            f"min_duration={_min_duration!r}, "
            f"max_duration={_max_duration!r}, "
            f"day_of_week={_day_of_week!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _start_time=(
            self.start_time
            if hasattr(self, "start_time")
            else None
        )
        _end_time=(
            self.end_time
            if hasattr(self, "end_time")
            else None
        )
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _min_kwh=(
            self.min_kwh
            if hasattr(self, "min_kwh")
            else None
        )
        _max_kwh=(
            self.max_kwh
            if hasattr(self, "max_kwh")
            else None
        )
        _min_current=(
            self.min_current
            if hasattr(self, "min_current")
            else None
        )
        _max_current=(
            self.max_current
            if hasattr(self, "max_current")
            else None
        )
        _min_power=(
            self.min_power
            if hasattr(self, "min_power")
            else None
        )
        _max_power=(
            self.max_power
            if hasattr(self, "max_power")
            else None
        )
        _min_duration=(
            self.min_duration
            if hasattr(self, "min_duration")
            else None
        )
        _max_duration=(
            self.max_duration
            if hasattr(self, "max_duration")
            else None
        )
        _day_of_week=(
            self.day_of_week
            if hasattr(self, "day_of_week")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"start_time={_start_time!s}, "
            f"end_time={_end_time!s}, "
            f"start_date={_start_date!s}, "
            f"end_date={_end_date!s}, "
            f"min_kwh={_min_kwh!s}, "
            f"max_kwh={_max_kwh!s}, "
            f"min_current={_min_current!s}, "
            f"max_current={_max_current!s}, "
            f"min_power={_min_power!s}, "
            f"max_power={_max_power!s}, "
            f"min_duration={_min_duration!s}, "
            f"max_duration={_max_duration!s}, "
            f"day_of_week={_day_of_week!s}, "
            f")"
        )
