"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.search_by_id_location_respone import (
    SearchByIdLocationRespone,
)


class SearchByIdResponse(object):
    """Implementation of the 'SearchByIdResponse' model.

    Attributes:
        request_id (uuid|str): requestId is unique identifier value that is attached
            to requests and messages that allow reference to a particular transaction
            or event chain.
        status (str): status of the API call
        data (List[SearchByIdLocationRespone]): API Response

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_id": "requestId",
        "status": "status",
        "data": "data",
    }

    _optionals = [
        "request_id",
        "status",
        "data",
    ]

    def __init__(
        self,
        request_id=APIHelper.SKIP,
        status=APIHelper.SKIP,
        data=APIHelper.SKIP):
        """Initialize a SearchByIdResponse instance."""
        # Initialize members of the class
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id
        if status is not APIHelper.SKIP:
            self.status = status
        if data is not APIHelper.SKIP:
            self.data = data

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        request_id =\
            dictionary.get("requestId")\
            if dictionary.get("requestId")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        data = None
        if dictionary.get("data") is not None:
            data = [
                SearchByIdLocationRespone.from_dictionary(x)
                    for x in dictionary.get("data")
            ]
        else:
            data = APIHelper.SKIP

        # Return an object of this model
        return cls(request_id,
                   status,
                   data)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _data=(
            self.data
            if hasattr(self, "data")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"request_id={_request_id!r}, "
            f"status={_status!r}, "
            f"data={_data!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _data=(
            self.data
            if hasattr(self, "data")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"request_id={_request_id!s}, "
            f"status={_status!s}, "
            f"data={_data!s}, "
            f")"
        )
