"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.search_by_id_connector import (
    SearchByIdConnector,
)


class SearchByIdEvse(object):
    """Implementation of the 'SearchByIdEvse' model.

    Each Location will contain one or more EVSEs (Electric Vehicle Supply Equipment).
    Each EVSE is capable of charging one car at a time.

    Attributes:
        uid (str): Internal identifier used to refer to single individual  EVSE unit.
        external_id (str): Identifier of the Evse as given by the Operator, unique
            for that Operator
        evse_id (str): Standard EVSEId identifier (ISO-IEC-15118)
        status (EvseVOStatusEnum): The current status of the EVSE units availability
        updated (str): ISO8601-compliant UTC datetime of the last update of the EVSE
        physical_reference (str): An optional number/string printed on the outside of
            the EVSE for visual identification
        connectors (List[SearchByIdConnector]): List of all connectors available on
            this EVSE unit.
        authorization_methods
            (List[SingleLocationMarkerAuthorizationMethodsItemsEnum]): Methods that
            can be used to Authorize sessions on this EVSE

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uid": "uid",
        "external_id": "externalId",
        "evse_id": "evseId",
        "status": "status",
        "updated": "updated",
        "physical_reference": "physicalReference",
        "connectors": "connectors",
        "authorization_methods": "authorizationMethods",
    }

    _optionals = [
        "uid",
        "external_id",
        "evse_id",
        "status",
        "updated",
        "physical_reference",
        "connectors",
        "authorization_methods",
    ]

    def __init__(
        self,
        uid=APIHelper.SKIP,
        external_id=APIHelper.SKIP,
        evse_id=APIHelper.SKIP,
        status=APIHelper.SKIP,
        updated=APIHelper.SKIP,
        physical_reference=APIHelper.SKIP,
        connectors=APIHelper.SKIP,
        authorization_methods=APIHelper.SKIP):
        """Initialize a SearchByIdEvse instance."""
        # Initialize members of the class
        if uid is not APIHelper.SKIP:
            self.uid = uid
        if external_id is not APIHelper.SKIP:
            self.external_id = external_id
        if evse_id is not APIHelper.SKIP:
            self.evse_id = evse_id
        if status is not APIHelper.SKIP:
            self.status = status
        if updated is not APIHelper.SKIP:
            self.updated = updated
        if physical_reference is not APIHelper.SKIP:
            self.physical_reference = physical_reference
        if connectors is not APIHelper.SKIP:
            self.connectors = connectors
        if authorization_methods is not APIHelper.SKIP:
            self.authorization_methods = authorization_methods

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        uid =\
            dictionary.get("uid")\
            if dictionary.get("uid")\
                else APIHelper.SKIP
        external_id =\
            dictionary.get("externalId")\
            if dictionary.get("externalId")\
                else APIHelper.SKIP
        evse_id =\
            dictionary.get("evseId")\
            if dictionary.get("evseId")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        updated =\
            dictionary.get("updated")\
            if dictionary.get("updated")\
                else APIHelper.SKIP
        physical_reference =\
            dictionary.get("physicalReference")\
            if dictionary.get("physicalReference")\
                else APIHelper.SKIP
        connectors = None
        if dictionary.get("connectors") is not None:
            connectors = [
                SearchByIdConnector.from_dictionary(x)
                    for x in dictionary.get("connectors")
            ]
        else:
            connectors = APIHelper.SKIP
        authorization_methods =\
            dictionary.get("authorizationMethods")\
            if dictionary.get("authorizationMethods")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(uid,
                   external_id,
                   evse_id,
                   status,
                   updated,
                   physical_reference,
                   connectors,
                   authorization_methods)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _uid=(
            self.uid
            if hasattr(self, "uid")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _evse_id=(
            self.evse_id
            if hasattr(self, "evse_id")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _updated=(
            self.updated
            if hasattr(self, "updated")
            else None
        )
        _physical_reference=(
            self.physical_reference
            if hasattr(self, "physical_reference")
            else None
        )
        _connectors=(
            self.connectors
            if hasattr(self, "connectors")
            else None
        )
        _authorization_methods=(
            self.authorization_methods
            if hasattr(self, "authorization_methods")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"uid={_uid!r}, "
            f"external_id={_external_id!r}, "
            f"evse_id={_evse_id!r}, "
            f"status={_status!r}, "
            f"updated={_updated!r}, "
            f"physical_reference={_physical_reference!r}, "
            f"connectors={_connectors!r}, "
            f"authorization_methods={_authorization_methods!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _uid=(
            self.uid
            if hasattr(self, "uid")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _evse_id=(
            self.evse_id
            if hasattr(self, "evse_id")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _updated=(
            self.updated
            if hasattr(self, "updated")
            else None
        )
        _physical_reference=(
            self.physical_reference
            if hasattr(self, "physical_reference")
            else None
        )
        _connectors=(
            self.connectors
            if hasattr(self, "connectors")
            else None
        )
        _authorization_methods=(
            self.authorization_methods
            if hasattr(self, "authorization_methods")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"uid={_uid!s}, "
            f"external_id={_external_id!s}, "
            f"evse_id={_evse_id!s}, "
            f"status={_status!s}, "
            f"updated={_updated!s}, "
            f"physical_reference={_physical_reference!s}, "
            f"connectors={_connectors!s}, "
            f"authorization_methods={_authorization_methods!s}, "
            f")"
        )
