"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.accessibility_v_2 import (
    AccessibilityV2,
)
from shellev.models.address import Address
from shellev.models.coordinates import Coordinates
from shellev.models.opening_hours_object import (
    OpeningHoursObject,
)
from shellev.models.search_by_id_evse import (
    SearchByIdEvse,
)


class SearchByIdLocationRespone(object):
    """Implementation of the 'SearchByIdLocationRespone' model.

    Attributes:
        uid (str): Unique Internal identifier used to refer to this Location by Shell
            Recharge
        external_id (str): Identifier as given by the Shell Recharge Operator, unique
            for that Operator
        coordinates (Coordinates): Coordinates of the Shell Recharge Site Location
        operator_name (str): Operator of this Shell Recharge Location
        address (Address): Address of the Shell Recharge Location
        accessibility (AccessibilityV2): Accessibility of the Location
        evses (List[SearchByIdEvse]): The model property of type List[SearchByIdEvse].
        opening_hours (List[OpeningHoursObject]): Optional Opening Hours of the
            Location. Please note that it is not available for all sites.
        updated (str): ISO8601-compliant UTC datetime of the last update of the
            location
        location_type (str): the type of the location. Could be "UNKNOWN".
        operator_id (str): Unique Id of the operator
        open_twenty_four_seven (bool): Whether the location is open 24/7

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uid": "uid",
        "external_id": "externalId",
        "coordinates": "coordinates",
        "operator_name": "operatorName",
        "address": "address",
        "accessibility": "accessibility",
        "evses": "evses",
        "opening_hours": "openingHours",
        "updated": "updated",
        "location_type": "locationType",
        "operator_id": "operatorId",
        "open_twenty_four_seven": "openTwentyFourSeven",
    }

    _optionals = [
        "uid",
        "external_id",
        "coordinates",
        "operator_name",
        "address",
        "accessibility",
        "evses",
        "opening_hours",
        "updated",
        "location_type",
        "operator_id",
        "open_twenty_four_seven",
    ]

    def __init__(
        self,
        uid=APIHelper.SKIP,
        external_id=APIHelper.SKIP,
        coordinates=APIHelper.SKIP,
        operator_name=APIHelper.SKIP,
        address=APIHelper.SKIP,
        accessibility=APIHelper.SKIP,
        evses=APIHelper.SKIP,
        opening_hours=APIHelper.SKIP,
        updated=APIHelper.SKIP,
        location_type=APIHelper.SKIP,
        operator_id=APIHelper.SKIP,
        open_twenty_four_seven=APIHelper.SKIP):
        """Initialize a SearchByIdLocationRespone instance."""
        # Initialize members of the class
        if uid is not APIHelper.SKIP:
            self.uid = uid
        if external_id is not APIHelper.SKIP:
            self.external_id = external_id
        if coordinates is not APIHelper.SKIP:
            self.coordinates = coordinates
        if operator_name is not APIHelper.SKIP:
            self.operator_name = operator_name
        if address is not APIHelper.SKIP:
            self.address = address
        if accessibility is not APIHelper.SKIP:
            self.accessibility = accessibility
        if evses is not APIHelper.SKIP:
            self.evses = evses
        if opening_hours is not APIHelper.SKIP:
            self.opening_hours = opening_hours
        if updated is not APIHelper.SKIP:
            self.updated = updated
        if location_type is not APIHelper.SKIP:
            self.location_type = location_type
        if operator_id is not APIHelper.SKIP:
            self.operator_id = operator_id
        if open_twenty_four_seven is not APIHelper.SKIP:
            self.open_twenty_four_seven = open_twenty_four_seven

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        uid =\
            dictionary.get("uid")\
            if dictionary.get("uid")\
                else APIHelper.SKIP
        external_id =\
            dictionary.get("externalId")\
            if dictionary.get("externalId")\
                else APIHelper.SKIP
        coordinates =\
            Coordinates.from_dictionary(
                dictionary.get("coordinates"))\
                if "coordinates" in dictionary.keys()\
                else APIHelper.SKIP
        operator_name =\
            dictionary.get("operatorName")\
            if dictionary.get("operatorName")\
                else APIHelper.SKIP
        address =\
            Address.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP
        accessibility =\
            AccessibilityV2.from_dictionary(
                dictionary.get("accessibility"))\
                if "accessibility" in dictionary.keys()\
                else APIHelper.SKIP
        evses = None
        if dictionary.get("evses") is not None:
            evses = [
                SearchByIdEvse.from_dictionary(x)
                    for x in dictionary.get("evses")
            ]
        else:
            evses = APIHelper.SKIP
        opening_hours = None
        if dictionary.get("openingHours") is not None:
            opening_hours = [
                OpeningHoursObject.from_dictionary(x)
                    for x in dictionary.get("openingHours")
            ]
        else:
            opening_hours = APIHelper.SKIP
        updated =\
            dictionary.get("updated")\
            if dictionary.get("updated")\
                else APIHelper.SKIP
        location_type =\
            dictionary.get("locationType")\
            if dictionary.get("locationType")\
                else APIHelper.SKIP
        operator_id =\
            dictionary.get("operatorId")\
            if dictionary.get("operatorId")\
                else APIHelper.SKIP
        open_twenty_four_seven =\
            dictionary.get("openTwentyFourSeven")\
            if "openTwentyFourSeven" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(uid,
                   external_id,
                   coordinates,
                   operator_name,
                   address,
                   accessibility,
                   evses,
                   opening_hours,
                   updated,
                   location_type,
                   operator_id,
                   open_twenty_four_seven)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _uid=(
            self.uid
            if hasattr(self, "uid")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _coordinates=(
            self.coordinates
            if hasattr(self, "coordinates")
            else None
        )
        _operator_name=(
            self.operator_name
            if hasattr(self, "operator_name")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _accessibility=(
            self.accessibility
            if hasattr(self, "accessibility")
            else None
        )
        _evses=(
            self.evses
            if hasattr(self, "evses")
            else None
        )
        _opening_hours=(
            self.opening_hours
            if hasattr(self, "opening_hours")
            else None
        )
        _updated=(
            self.updated
            if hasattr(self, "updated")
            else None
        )
        _location_type=(
            self.location_type
            if hasattr(self, "location_type")
            else None
        )
        _operator_id=(
            self.operator_id
            if hasattr(self, "operator_id")
            else None
        )
        _open_twenty_four_seven=(
            self.open_twenty_four_seven
            if hasattr(self, "open_twenty_four_seven")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"uid={_uid!r}, "
            f"external_id={_external_id!r}, "
            f"coordinates={_coordinates!r}, "
            f"operator_name={_operator_name!r}, "
            f"address={_address!r}, "
            f"accessibility={_accessibility!r}, "
            f"evses={_evses!r}, "
            f"opening_hours={_opening_hours!r}, "
            f"updated={_updated!r}, "
            f"location_type={_location_type!r}, "
            f"operator_id={_operator_id!r}, "
            f"open_twenty_four_seven={_open_twenty_four_seven!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _uid=(
            self.uid
            if hasattr(self, "uid")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _coordinates=(
            self.coordinates
            if hasattr(self, "coordinates")
            else None
        )
        _operator_name=(
            self.operator_name
            if hasattr(self, "operator_name")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _accessibility=(
            self.accessibility
            if hasattr(self, "accessibility")
            else None
        )
        _evses=(
            self.evses
            if hasattr(self, "evses")
            else None
        )
        _opening_hours=(
            self.opening_hours
            if hasattr(self, "opening_hours")
            else None
        )
        _updated=(
            self.updated
            if hasattr(self, "updated")
            else None
        )
        _location_type=(
            self.location_type
            if hasattr(self, "location_type")
            else None
        )
        _operator_id=(
            self.operator_id
            if hasattr(self, "operator_id")
            else None
        )
        _open_twenty_four_seven=(
            self.open_twenty_four_seven
            if hasattr(self, "open_twenty_four_seven")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"uid={_uid!s}, "
            f"external_id={_external_id!s}, "
            f"coordinates={_coordinates!s}, "
            f"operator_name={_operator_name!s}, "
            f"address={_address!s}, "
            f"accessibility={_accessibility!s}, "
            f"evses={_evses!s}, "
            f"opening_hours={_opening_hours!s}, "
            f"updated={_updated!s}, "
            f"location_type={_location_type!s}, "
            f"operator_id={_operator_id!s}, "
            f"open_twenty_four_seven={_open_twenty_four_seven!s}, "
            f")"
        )
