"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.coordinates import Coordinates


class SingleLocationMarkerV2(object):
    """Implementation of the 'SingleLocationMarkerV2' model.

    A Marker is a place on the map that represent a single Location

    Attributes:
        status (SingleLocationMarkerStatusEnum): Minimum of all status values in the
            Marker, e.g. if at least one Evse in the Marker is available, the value
            will be available
        coordinates (Coordinates): Coordinates of the Shell Recharge Site Location
        evse_count (float): Total number of Evse units in Locations that this Marker
            represents
        max_power (float): Maximum power in kW across all locations grouped in this
            marker (disregarding availability)
        location_count (float): Number of Locations that this Marker represents in
            the given set of bounds
        location_uid (str): Unique ID of the Location this Marker represents
        authorization_methods
            (List[SingleLocationMarkerAuthorizationMethodsItemsEnum]): Methods that
            can be used to Authorize sessions on this EVSE
        operator_name (str): Operator of this Shell Recharge Location
        marker_type (str): Type of the Marker, in this case it will always be
            SingleLocation

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "marker_type": "markerType",
        "status": "status",
        "coordinates": "coordinates",
        "evse_count": "evseCount",
        "max_power": "maxPower",
        "location_count": "locationCount",
        "location_uid": "locationUid",
        "authorization_methods": "authorizationMethods",
        "operator_name": "operatorName",
    }

    _optionals = [
        "status",
        "coordinates",
        "evse_count",
        "max_power",
        "location_count",
        "location_uid",
        "authorization_methods",
        "operator_name",
    ]

    def __init__(
        self,
        status=APIHelper.SKIP,
        coordinates=APIHelper.SKIP,
        evse_count=APIHelper.SKIP,
        max_power=APIHelper.SKIP,
        location_count=APIHelper.SKIP,
        location_uid=APIHelper.SKIP,
        authorization_methods=APIHelper.SKIP,
        operator_name=APIHelper.SKIP):
        """Initialize a SingleLocationMarkerV2 instance."""
        # Initialize members of the class
        if status is not APIHelper.SKIP:
            self.status = status
        if coordinates is not APIHelper.SKIP:
            self.coordinates = coordinates
        if evse_count is not APIHelper.SKIP:
            self.evse_count = evse_count
        if max_power is not APIHelper.SKIP:
            self.max_power = max_power
        if location_count is not APIHelper.SKIP:
            self.location_count = location_count
        if location_uid is not APIHelper.SKIP:
            self.location_uid = location_uid
        if authorization_methods is not APIHelper.SKIP:
            self.authorization_methods = authorization_methods
        if operator_name is not APIHelper.SKIP:
            self.operator_name = operator_name
        self.marker_type = "SingleLocation"

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        coordinates =\
            Coordinates.from_dictionary(
                dictionary.get("coordinates"))\
                if "coordinates" in dictionary.keys()\
                else APIHelper.SKIP
        evse_count =\
            dictionary.get("evseCount")\
            if dictionary.get("evseCount")\
                else APIHelper.SKIP
        max_power =\
            dictionary.get("maxPower")\
            if dictionary.get("maxPower")\
                else APIHelper.SKIP
        location_count =\
            dictionary.get("locationCount")\
            if dictionary.get("locationCount")\
                else APIHelper.SKIP
        location_uid =\
            dictionary.get("locationUid")\
            if dictionary.get("locationUid")\
                else APIHelper.SKIP
        authorization_methods =\
            dictionary.get("authorizationMethods")\
            if dictionary.get("authorizationMethods")\
                else APIHelper.SKIP
        operator_name =\
            dictionary.get("operatorName")\
            if dictionary.get("operatorName")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(status,
                   coordinates,
                   evse_count,
                   max_power,
                   location_count,
                   location_uid,
                   authorization_methods,
                   operator_name)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.marker_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("markerType"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _coordinates=(
            self.coordinates
            if hasattr(self, "coordinates")
            else None
        )
        _evse_count=(
            self.evse_count
            if hasattr(self, "evse_count")
            else None
        )
        _max_power=(
            self.max_power
            if hasattr(self, "max_power")
            else None
        )
        _location_count=(
            self.location_count
            if hasattr(self, "location_count")
            else None
        )
        _location_uid=(
            self.location_uid
            if hasattr(self, "location_uid")
            else None
        )
        _authorization_methods=(
            self.authorization_methods
            if hasattr(self, "authorization_methods")
            else None
        )
        _operator_name=(
            self.operator_name
            if hasattr(self, "operator_name")
            else None
        )
        _marker_type=self.marker_type
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f"coordinates={_coordinates!r}, "
            f"evse_count={_evse_count!r}, "
            f"max_power={_max_power!r}, "
            f"location_count={_location_count!r}, "
            f"location_uid={_location_uid!r}, "
            f"authorization_methods={_authorization_methods!r}, "
            f"operator_name={_operator_name!r}, "
            f"marker_type={_marker_type!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _coordinates=(
            self.coordinates
            if hasattr(self, "coordinates")
            else None
        )
        _evse_count=(
            self.evse_count
            if hasattr(self, "evse_count")
            else None
        )
        _max_power=(
            self.max_power
            if hasattr(self, "max_power")
            else None
        )
        _location_count=(
            self.location_count
            if hasattr(self, "location_count")
            else None
        )
        _location_uid=(
            self.location_uid
            if hasattr(self, "location_uid")
            else None
        )
        _authorization_methods=(
            self.authorization_methods
            if hasattr(self, "authorization_methods")
            else None
        )
        _operator_name=(
            self.operator_name
            if hasattr(self, "operator_name")
            else None
        )
        _marker_type=self.marker_type
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f"coordinates={_coordinates!s}, "
            f"evse_count={_evse_count!s}, "
            f"max_power={_max_power!s}, "
            f"location_count={_location_count!s}, "
            f"location_uid={_location_uid!s}, "
            f"authorization_methods={_authorization_methods!s}, "
            f"operator_name={_operator_name!s}, "
            f"marker_type={_marker_type!s}, "
            f")"
        )
