# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SingleLocationMarkerStatusEnum(object):

    """Implementation of the 'SingleLocationMarkerStatus' enum.

    Minimum of all status values in the Marker, e.g. if at least one Evse in
    the Marker is available, the value will be available

    Attributes:
        AVAILABLE: TODO: type description here.
        OCCUPIED: TODO: type description here.
        UNAVAILABLE: TODO: type description here.
        UNKNOWN: TODO: type description here.

    """
    _all_values = ['Available', 'Occupied', 'Unavailable', 'Unknown']
    AVAILABLE = 'Available'

    OCCUPIED = 'Occupied'

    UNAVAILABLE = 'Unavailable'

    UNKNOWN = 'Unknown'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   