# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StopChargeSessionRequestBodyJson(object):

    """Implementation of the 'stopChargeSessionRequestBodyJson' model.

    TODO: type model description here.

    Attributes:
        sesssion_id (str): Session Id is to be fetched

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sesssion_id": 'SesssionId'
    }

    def __init__(self,
                 sesssion_id=None):
        """Constructor for the StopChargeSessionRequestBodyJson class"""

        # Initialize members of the class
        self.sesssion_id = sesssion_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        sesssion_id = dictionary.get("SesssionId") if dictionary.get("SesssionId") else None
        # Return an object of this model
        return cls(sesssion_id)
