"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.power_range import PowerRange
from shellev.models.tariff_alt_text import TariffAltText
from shellev.models.tariff_element import TariffElement


class TariffV2(object):
    """Implementation of the 'TariffV2' model.

    Tariff metadata aligned with TariffV2 GraphQL schema

    Attributes:
        tariff_id (str): Unique identifier for the tariff
        tariff_type (TariffTypeEnum): Tariff type classification
        power_range (PowerRange): The model property of type PowerRange.
        internal_id (str): Internal identifier used by the platform
        operator_id (str): Unique identifier of the operator
        provider_id (str): Unique identifier of the provider
        currency (str): ISO 4217 Currency Code
        tariff_alt_text (List[TariffAltText]): The model property of type
            List[TariffAltText].
        min_price (float): The model property of type float.
        max_price (float): The model property of type float.
        elements (List[TariffElement]): The model property of type
            List[TariffElement].
        start_date_time (datetime): The model property of type datetime.
        end_date_time (datetime): The model property of type datetime.
        last_updated (datetime): The model property of type datetime.
        created_by (str): Identifier of the actor who created the tariff

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tariff_id": "tariffId",
        "tariff_type": "tariffType",
        "power_range": "powerRange",
        "internal_id": "internalId",
        "operator_id": "operatorId",
        "provider_id": "providerId",
        "currency": "currency",
        "tariff_alt_text": "tariffAltText",
        "min_price": "minPrice",
        "max_price": "maxPrice",
        "elements": "elements",
        "start_date_time": "startDateTime",
        "end_date_time": "endDateTime",
        "last_updated": "lastUpdated",
        "created_by": "createdBy",
    }

    _nullables = [
        "tariff_alt_text",
    ]

    def __init__(
        self,
        tariff_id=None,
        tariff_type=None,
        power_range=None,
        internal_id=None,
        operator_id=None,
        provider_id=None,
        currency=None,
        tariff_alt_text=None,
        min_price=None,
        max_price=None,
        elements=None,
        start_date_time=None,
        end_date_time=None,
        last_updated=None,
        created_by=None):
        """Initialize a TariffV2 instance."""
        # Initialize members of the class
        self.tariff_id = tariff_id
        self.tariff_type = tariff_type
        self.power_range = power_range
        self.internal_id = internal_id
        self.operator_id = operator_id
        self.provider_id = provider_id
        self.currency = currency
        self.tariff_alt_text = tariff_alt_text
        self.min_price = min_price
        self.max_price = max_price
        self.elements = elements
        self.start_date_time =\
             APIHelper.apply_datetime_converter(
            start_date_time, APIHelper.RFC3339DateTime)\
             if start_date_time else None
        self.end_date_time =\
             APIHelper.apply_datetime_converter(
            end_date_time, APIHelper.RFC3339DateTime)\
             if end_date_time else None
        self.last_updated =\
             APIHelper.apply_datetime_converter(
            last_updated, APIHelper.RFC3339DateTime)\
             if last_updated else None
        self.created_by = created_by

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tariff_id =\
            dictionary.get("tariffId")\
            if dictionary.get("tariffId")\
                else None
        tariff_type =\
            dictionary.get("tariffType")\
            if dictionary.get("tariffType")\
                else None
        power_range =\
            PowerRange.from_dictionary(
                dictionary.get("powerRange"))\
                if dictionary.get("powerRange") else None
        internal_id =\
            dictionary.get("internalId")\
            if dictionary.get("internalId")\
                else None
        operator_id =\
            dictionary.get("operatorId")\
            if dictionary.get("operatorId")\
                else None
        provider_id =\
            dictionary.get("providerId")\
            if dictionary.get("providerId")\
                else None
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else None
        tariff_alt_text = None
        if dictionary.get("tariffAltText") is not None:
            tariff_alt_text = [
                TariffAltText.from_dictionary(x)
                    for x in dictionary.get("tariffAltText")
            ]
        min_price =\
            dictionary.get("minPrice")\
            if dictionary.get("minPrice")\
                else None
        max_price =\
            dictionary.get("maxPrice")\
            if dictionary.get("maxPrice")\
                else None
        elements = None
        if dictionary.get("elements") is not None:
            elements = [
                TariffElement.from_dictionary(x)
                    for x in dictionary.get("elements")
            ]
        start_date_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("startDateTime")).datetime\
            if dictionary.get("startDateTime") else None
        end_date_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("endDateTime")).datetime\
            if dictionary.get("endDateTime") else None
        last_updated = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("lastUpdated")).datetime\
            if dictionary.get("lastUpdated") else None
        created_by =\
            dictionary.get("createdBy")\
            if dictionary.get("createdBy")\
                else None

        # Return an object of this model
        return cls(tariff_id,
                   tariff_type,
                   power_range,
                   internal_id,
                   operator_id,
                   provider_id,
                   currency,
                   tariff_alt_text,
                   min_price,
                   max_price,
                   elements,
                   start_date_time,
                   end_date_time,
                   last_updated,
                   created_by)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _tariff_id=self.tariff_id
        _tariff_type=self.tariff_type
        _power_range=self.power_range
        _internal_id=self.internal_id
        _operator_id=self.operator_id
        _provider_id=self.provider_id
        _currency=self.currency
        _tariff_alt_text=self.tariff_alt_text
        _min_price=self.min_price
        _max_price=self.max_price
        _elements=self.elements
        _start_date_time=self.start_date_time
        _end_date_time=self.end_date_time
        _last_updated=self.last_updated
        _created_by=self.created_by
        return (
            f"{self.__class__.__name__}("
            f"tariff_id={_tariff_id!r}, "
            f"tariff_type={_tariff_type!r}, "
            f"power_range={_power_range!r}, "
            f"internal_id={_internal_id!r}, "
            f"operator_id={_operator_id!r}, "
            f"provider_id={_provider_id!r}, "
            f"currency={_currency!r}, "
            f"tariff_alt_text={_tariff_alt_text!r}, "
            f"min_price={_min_price!r}, "
            f"max_price={_max_price!r}, "
            f"elements={_elements!r}, "
            f"start_date_time={_start_date_time!r}, "
            f"end_date_time={_end_date_time!r}, "
            f"last_updated={_last_updated!r}, "
            f"created_by={_created_by!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _tariff_id=self.tariff_id
        _tariff_type=self.tariff_type
        _power_range=self.power_range
        _internal_id=self.internal_id
        _operator_id=self.operator_id
        _provider_id=self.provider_id
        _currency=self.currency
        _tariff_alt_text=self.tariff_alt_text
        _min_price=self.min_price
        _max_price=self.max_price
        _elements=self.elements
        _start_date_time=self.start_date_time
        _end_date_time=self.end_date_time
        _last_updated=self.last_updated
        _created_by=self.created_by
        return (
            f"{self.__class__.__name__}("
            f"tariff_id={_tariff_id!s}, "
            f"tariff_type={_tariff_type!s}, "
            f"power_range={_power_range!s}, "
            f"internal_id={_internal_id!s}, "
            f"operator_id={_operator_id!s}, "
            f"provider_id={_provider_id!s}, "
            f"currency={_currency!s}, "
            f"tariff_alt_text={_tariff_alt_text!s}, "
            f"min_price={_min_price!s}, "
            f"max_price={_max_price!s}, "
            f"elements={_elements!s}, "
            f"start_date_time={_start_date_time!s}, "
            f"end_date_time={_end_date_time!s}, "
            f"last_updated={_last_updated!s}, "
            f"created_by={_created_by!s}, "
            f")"
        )
