"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.models.price_component import PriceComponent
from shellev.models.restrictions import Restrictions


class TariffElement(object):
    """Implementation of the 'TariffElement' model.

    Attributes:
        price_components (List[PriceComponent]): The model property of type
            List[PriceComponent].
        restrictions (Restrictions): The model property of type Restrictions.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "price_components": "priceComponents",
        "restrictions": "restrictions",
    }

    _optionals = [
        "restrictions",
    ]

    def __init__(
        self,
        price_components=None,
        restrictions=APIHelper.SKIP):
        """Initialize a TariffElement instance."""
        # Initialize members of the class
        self.price_components = price_components
        if restrictions is not APIHelper.SKIP:
            self.restrictions = restrictions

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        price_components = None
        if dictionary.get("priceComponents") is not None:
            price_components = [
                PriceComponent.from_dictionary(x)
                    for x in dictionary.get("priceComponents")
            ]
        restrictions =\
            Restrictions.from_dictionary(
                dictionary.get("restrictions"))\
                if "restrictions" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(price_components,
                   restrictions)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _price_components=self.price_components
        _restrictions=(
            self.restrictions
            if hasattr(self, "restrictions")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"price_components={_price_components!r}, "
            f"restrictions={_restrictions!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _price_components=self.price_components
        _restrictions=(
            self.restrictions
            if hasattr(self, "restrictions")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"price_components={_price_components!s}, "
            f"restrictions={_restrictions!s}, "
            f")"
        )
