# -*- coding: utf-8 -*-

"""
shellev

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TariffVOUpdatedByEnum(object):

    """Implementation of the 'tariffVOUpdatedBy' enum.

    Source of the last update of the tariff details

    Attributes:
        FEED: The enum member of type str.
        ADMIN: The enum member of type str.
        TARIFFSERVICE: The enum member of type str.
        DEFAULTS: The enum member of type str.

    """
    FEED = 'Feed'

    ADMIN = 'Admin'

    TARIFFSERVICE = 'TariffService'

    DEFAULTS = 'Defaults'

