"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class TariffAltText(object):
    """Implementation of the 'TariffAltText' model.

    Attributes:
        language (str): ISO language code
        text (str): Human readable tariff description

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "language": "language",
        "text": "text",
    }

    def __init__(
        self,
        language=None,
        text=None):
        """Initialize a TariffAltText instance."""
        # Initialize members of the class
        self.language = language
        self.text = text

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        language =\
            dictionary.get("language")\
            if dictionary.get("language")\
                else None
        text =\
            dictionary.get("text")\
            if dictionary.get("text")\
                else None

        # Return an object of this model
        return cls(language,
                   text)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _language=self.language
        _text=self.text
        return (
            f"{self.__class__.__name__}("
            f"language={_language!r}, "
            f"text={_text!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _language=self.language
        _text=self.text
        return (
            f"{self.__class__.__name__}("
            f"language={_language!s}, "
            f"text={_text!s}, "
            f")"
        )
