"""shellev.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from shellev.api_helper import APIHelper
from shellev.exceptions.api_exception import (
    APIException,
)
from shellev.models.not_found_err_msg import (
    NotFoundErrMsg,
)


class V2ChargeSessionRetrieve404ErrorException(APIException):
    def __init__(self, reason, response):
        """Initialize V2ChargeSessionRetrieve404ErrorException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(V2ChargeSessionRetrieve404ErrorException,
              self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.request_id =\
            dictionary.get("requestId")\
            if dictionary.get("requestId")\
                else None
        self.status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        self.errors = None
        if dictionary.get("errors") is not None:
            self.errors = [
                NotFoundErrMsg.from_dictionary(x)
                    for x in dictionary.get("errors")
            ]
        else:
            self.errors = None


    def __str__(self):
        """Return a human-readable string representation."""
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _errors=(
            self.errors
            if hasattr(self, "errors")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"request_id={_request_id!s}, "
            f"status={_status!s}, "
            f"errors={_errors!s}, "
            f")"
        )
